### ISSUE TITLE
Make CPPE pip-installable

### ISSUE THREAD

**Issue by maxscheurer** [maxscheurer/cppe#10]
The compiled Python interface should be installable via `pip`, making integration in Python packages easier (e.g., `pyscf`). 

- [ ] minimal `setup.py` to trigger build via `cmake`
- [ ] install the resulting `cppe.cpython-37m*.so` library
- [x] run tests via `python3 setup.py test`

**Comment by robertodr** [comment]
This might be of interest: https://github.com/dev-cafe/cmake-cookbook/tree/master/chapter-11/recipe-02
