### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by maxscheurer** [maxscheurer/cppe#11]
- [x] use `<algorithm>` when possible...
- [x] remove unused code
- [x] make a header for each source file
- [ ] refactor `libcppe.hh` (Related to #3)
- [x] more pythonic handling of PE Options (#16)
- [ ] multiply pre-factors with moments?
- [x] more pythonic handling of PE Energies (dictionary)
- [x] more pythonic exposure of properties (`get_site_position()`, `get_values()`)
- [x] clang-format on all files

**Comment by dgasmith** [comment]
If you haven't done so already might be worth running `clang-format` over the code for consistency.

**Comment by mfherbst** [comment]
@maxscheurer This might be helpful on that note: https://github.com/mfherbst/ctx/blob/master/scripts/run-clang-format.py

**Comment by maxscheurer** [comment]
Thanks! Will be merged in #17
