### ISSUE TITLE
v0.1.1

### ISSUE THREAD

**Issue by loriab** [maxscheurer/cppe#18]
On Linux conda the new v0.0.9 builds just fine (https://anaconda.org/psi4/pycppe/files and https://anaconda.org/psi4/cppe/files). Request that you splurge on the next version and make it v0.2 so it sorts after the dummy v0.1 tag I had used originally.

**Comment by maxscheurer** [comment]
Would v0.1.1 also be an option to solve this problem? 😄

**Comment by loriab** [comment]
Yes, v0.1.1 would do nicely sorting-wise. FYI that for projects in useable state (as cppe def. is), incrementing minor would be more usual (e.g., https://github.com/samuelcolvin/pydantic/releases).

**Comment by loriab** [comment]
conda build on Mac is also ok https://anaconda.org/psi4/pycppe/files

**Comment by maxscheurer** [comment]
Awesome! 👍 
Thanks, @loriab.
